- include: apt.yml
  when: ansible_distribution_file_variety == 'Debian'

- include: yum.yml
  when: ansible_distribution_file_variety == 'RedHat'

- name: Create NVM install dir
  file:
    path: "{{ nvm_install_dir }}"
    state: directory
    mode: 0755

- name: Set fact 'theia_ide_user' when not defined
  set_fact:
    theia_ide_user: "{{ ansible_env.SUDO_USER }}"
  when: theia_ide_user is not defined

- name: Set fact 'theia_ide_workspace' when not defined
  set_fact:
    theia_ide_workspace: "{{ ansible_env.PWD }}"
  when: theia_ide_workspace is not defined

- name: Create Theia directories
  file:
    path: "{{item}}"
    state: directory
    recurse: True
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_gid}}"
    mode: 0755
  with_items:
    - "{{theia_package_json.theiaPluginsDir}}"
    - "{{theia_ide_workspace}}"
    - "{{theia_ide_dir}}/extensions"

- name: Install nvm
  shell: |
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | NVM_DIR={{ nvm_install_dir }} /bin/bash
  args:
    creates: "{{ nvm_install_dir }}/nvm.sh"
    warn: false

#ToDo Check if yarn exists
- name: Install node 10 and yarn
  shell: |
        source {{ nvm_install_dir }}/nvm.sh
        nvm install 10
        npm install -g yarn
  args:
    executable: bash

- name: Create IDE build dir
  file:
    path: "{{ theia_ide_install_dir }}"
    state: directory

- name: Debug
  debug:
    var: theia_package_json
    verbosity: 2

- name: Template IDE configuration to IDE build dir
  template:
    src: package.json.j2
    #content: "{{theia_package_json}}"
    dest: "{{ theia_ide_install_dir }}/package.json"
    mode: 0644

#ToDo Only if package.json changed
#ToDo Notify restart theia service
- name: build ide
  shell: |
        source {{ nvm_install_dir }}/nvm.sh
        yarn
        yarn theia build
  args:
    chdir: "{{ theia_ide_install_dir }}"
    executable: bash

#ToDo Notify restart theia service
- name: Generate IDE start skript to /usr/local/bin
  template:
    src: theia-ide.sh.j2
    dest: "{{ theia_ide_install_dir }}/theia-ide.sh"
    mode: 0755

#ToDo Notify restart theia service
- name: Generate systemd service
  template:
    src: theia-ide.service.j2
    dest: /etc/systemd/system/theia-ide.service
    mode: 0644

#ToDo As handler
- name: Enable and Start service
  systemd:
    name: theia-ide.service
    enabled: true
    state: started
